### ISSUE TITLE
NoClassDefFoundError: Finalizer$ShutDown (wrong name: Finalizer) under webstart on OS X 10.4

### ISSUE THREAD

**Issue by gissuebot** [google/guava#312]
_[Original issue](https://code.google.com/p/guava-libraries/issues/detail?id=312) created by **jerith666** on 2010-01-12 at 05:59 PM_

---

Originally posted on SO, but redirected here by Kevin Bourrillion:

http://stackoverflow.com/questions/2049807/java-lang-noclassdeffounderror-com-google-common-base-internal-finalizershutdow

Our application uses the MapMaker class, and we're getting the exception
below, but only on OS X 10.4 using webstart. It works fine when launched
from an app bundle, and on OS X 10.5 and Windows.

This has started happening since our upgrade from RC2 to RC5 (we skipped
all the intervening versions). We've since upgraded to 1.0 final and still
see the issue.

I suspect some interaction with Sun's fix for this security issue [1](which changed the way that URL.toString%28%29 works in webstart), but don't
have any proof yet.

[1] http://sunsolve.sun.com/search/document.do?assetkey=1-66-238905-1

java.lang.NoClassDefFoundError:
com/google/common/base/internal/Finalizer$ShutDown (wrong name:
com/google/common/base/internal/Finalizer)
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2395)
at java.lang.Class.getMethod0(Class.java:2642)
at java.lang.Class.getMethod(Class.java:1579)
at
com.google.common.base.FinalizableReferenceQueue.getStartFinalizer(FinalizableReferenceQueue.java:308)
at
com.google.common.base.FinalizableReferenceQueue.&lt;clinit>(FinalizableReferenceQueue.java:102)
at com.google.common.collect.MapMaker$QueueHolder.&lt;clinit>(MapMaker.java:836)
at
com.google.common.collect.MapMaker$SoftValueReference.&lt;init>(MapMaker.java:1078)
at
com.google.common.collect.MapMaker$Strength$2.referenceValue(MapMaker.java:379)
at com.google.common.collect.MapMaker$StrategyImpl.setValue(MapMaker.java:488)
at com.google.common.collect.MapMaker$StrategyImpl.setValue(MapMaker.java:462)
at
com.google.common.collect.CustomConcurrentHashMap$Impl$Segment.put(CustomConcurrentHashMap.java:960)
at
com.google.common.collect.CustomConcurrentHashMap$Impl.put(CustomConcurrentHashMap.java:1438)
